version: "3.8"

services:
    postgres:
        image: postgres:16
        container_name: lemon_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: lemon_db
        ports:
            - "5402:5432"
        volumes:
            - lemon_data:/var/lib/postgresql/data
            # - ./data/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
    lemon_data:
